os:
  - linux

language:
  - cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq  # -qq No output except for errors

install:
  #-- Install cmake
  - sudo apt-get install cmake
  #-- Install yarp
  - git clone https://github.com/robotology/yarp
  - cd yarp && mkdir build && cd build
  - cmake .. -DSKIP_ACE=ON
  - make
  - sudo make install
  - cd ../..
  #-- Install kdl
  - sudo apt-get install libeigen3-dev
  - git clone -b issue78 https://github.com/jgvictores/orocos_kinematics_dynamics
  - cd orocos_kinematics_dynamics/orocos_kdl && mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../..
  #-- Install OpenRAVE
  - sudo apt-get install libboost-dev libboost-date-time-dev libboost-thread-dev
  - sudo apt-get install libqt4-dev qt4-dev-tools libxml2-dev libode-dev
  - sudo apt-get install libsoqt4-dev libcoin60-dev  # libcoin80-dev is not supported by current default travis
  - git clone --branch latest_stable https://github.com/rdiankov/openrave.git
  - cd openrave && mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # see http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
  - if [ "$CXX" = "g++" ]; then wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then tar xf lcov_1.11.orig.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then sudo make -C lcov-1.11/ install; fi
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

before_script:
  - mkdir -p build && cd build

script:
  - cmake .. -DENABLE_coverage=ON
  - make
  - sudo make install
  - bin/testKdlSolver

after_success:
  #  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - if [ "$CXX" = "g++" ]; then lcov --directory . --capture --output-file coverage.info; fi
  # filter out system and test code
  - if [ "$CXX" = "g++" ]; then lcov --remove coverage.info  '/usr/*' 'test/*' --output-file coverage.info; fi
  # debug before upload
  - if [ "$CXX" = "g++" ]; then lcov --list coverage.info; fi
  # uploads to coveralls
  #- if [ "$CXX" = "g++" ]; then coveralls-lcov --source-encoding=ISO-8859-1 --repo-token InWqFy6VWMrEUzr2Rn8XV0cGqv3wXWo2d coverage.info; fi
  - if [ "$CXX" = "g++" ]; then coveralls-lcov --source-encoding=ISO-8859-1 coverage.info; fi

  - sudo make uninstall

